### ISSUE TITLE
UDP bootloader application does not build

### ISSUE THREAD

**Issue by rockwarrior** [Microchip-MPLAB-Harmony/bootloader_apps_ethernet#1]
The UDP bootloader application does not build properly. There seems to be a missing dependency.

../src/config/sam_v71_xult/system/sys_random_h2_adapter.c:27:27: fatal error: crypto/crypto.h: No such file or directory
 #include "crypto/crypto.h"

MPLAB 5.40, XC32 2.41, Harmony3 3.8.1, SAME70_DFP 4.4.78, CMSIS 5.4.0

**Comment by Hrisikeshsahu** [comment]
Crypto module is required for the Net v3.6.4. The sys_random_h2_adapter has been updated to include the cryptographically secure random number generators. The sys_random_h2_adapter.c has been added to the net repo.

Solution -1  
------------------
To use crypto - please use this link https://github.com/Microchip-MPLAB-Harmony/crypto
and select "crypto engine" to the root project graph
I hope this will solve the build issue.

Solution -2
------------
Please use one of the previous version of net v3.6.4. This will solve the build issue.

**Comment by rockwarrior** [comment]
I see, thanks @Hrisikeshsahu. From the Harmony 3 Configurator GUI, it appears that the 3rd party wolfCrypt library is a dependency for the crypto library. So Solution 1 above will require both, correct?

**Comment by rockwarrior** [comment]
I'm going to take Solution 2 and down-rev my system until this base application is up to date with the latest frameworks.
